# Generated by Django 6.0.2 on 2026-02-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softserve", "0002_event_dashboard_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.TextField(blank=True, unique=True),
        ),
    ]
