# Generated by Django 6.0.2 on 2026-02-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softserve", "0003_alter_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
